# Change these first
owner: sakyey-dev # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Page
    url: https://sakyey.kr/about
  - name: User Page
    url: https://sakyey.kr/@sakyey
  - name: Generic API
    url: https://sakyey.kr/api/v1/instance
  - name: Streaming API
    url: https://sakyey.kr/api/v1/streaming/health
  - name: ActivityPub
    url: https://sakyey.kr/.well-known/webfinger?resource=acct:sakyey@sakyey.kr
assignees: # User to assign downtime issues (optional)
  - stevenoh0908

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sakyey.kr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/sakyey-dev/upptime/refs/heads/master/assets/sakyey_icon.svg
  name: sakyey.kr Status
  introTitle: "**사계 대광장(sakyey.kr)** 실시간 운영 현황"
  introMessage: "[사계 대광장](https://sakyey.kr)의 현재 **실시간** 운영 현황이에요. 서버가 아프거나 유지보수 작업 등으로 대광장 서비스가 중단되는 경우, 여기서 현재 서비스 상태 및 관련 안내를 확인하실 수 있어요. ― 서비스가 중단된 기간 동안 급한 사정이 있으시다면, [sakyey.official@gmail.com](mailto:sakyey.official@gmail.com)으로 문의해주세요!"
  navbar:
    - title: Status
      href: /
    - title: Sakyey
      href: https://sakyey.kr
  robotsText: "User-agent: * \n Disallow: /"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
