name: Announcements
description: Make a new announcement.
labels: ["announcement"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - info
        - warning
        - critical
    validations:
      required: true

  - type: textarea
    id: descriptions
    attributes:
      label: Descriptions
      description: Will be displayed on the status page, can use markdown syntax.
      placeholder: |
        Ex) There will be a regularly maintanance job from 02:00 to 04:00 on 1 Jan 2026.
        You may experience some service distruptions.
    validations:
      required: true

  - type: input
    id: expires
    attributes:
      label: Expires On (Optional)
      description: If not being left as blank, the announcement will be automatically closed after the specified date.
      placeholder: "YYYY-MM-DD"

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirm
      options:
        - label: I double-checked the content of this announcement.
          required: true
---
